# Database Configuration
# spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true&allowPublicKeyRetrieval=true&ssl-mode=REQUIRED
# spring.datasource.username=${DB_USER}
# spring.datasource.password=${DB_PASS}
# Hardcode for now just to get it LIVE
spring.datasource.url=jdbc:mysql://64.227.181.39:27761/defaultdb?useSSL=true&allowPublicKeyRetrieval=true&ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_AEc-F0ra67dEnEBjrKi
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Email Config for OTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.mail=DEBUG

# JWT Security Configuration
rasoi.jwt.secret=${JWT_SECRET}
rasoi.jwt.expiration=86400000

# Server Port
server.port=8080

# Cloudinary configuration
cloudinary.cloud_name=${CLOUDINARY_NAME}
cloudinary.api_key=${CLOUDINARY_KEY}
cloudinary.api_secret=${CLOUDINARY_SECRET}
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB